- name: Add Sublime Text apt key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add Sublime Text apt repository
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present

- name: Update packages
  apt:
    update_cache=yes

- name: Install Sublime Text via apt
  apt:
    name=sublime-text
    update_cache=yes
    cache_valid_time=86400
    install-recommends=no
    state=present
